# SPDX-License-Identifier: MPL-2.0
name: OSSF Scorecard
on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 4 * * 0'
permissions: read-all
jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
        with:
          persist-credentials: false
      - name: Run Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload results
        uses: github/codeql-action/upload-sarif@c73f0fa0f11186f652ae89bf78d969cf8af9f729 # v3
        with:
          sarif_file: results.sarif
